let euroCities = ["Paris", "London", "Valletta", "Prague", "Rome"];
let secondItem = euroCities[1];
console.log(secondItem);
euroCities[0] = "Berlin";
console.log(euroCities);
console.log(euroCities.length);
euroCities.pop();
console.log(euroCities);
console.log(euroCities.length);
euroCities[4] = "Budapest";
console.log(euroCities);
euroCities.splice(1,2);
console.log(euroCities);
let asianCities = ["Tokyo", "Hongkong", "Bangkok", "Manila", "Seoul"];
console.log(asianCities);
let another = asianCities.slice(1, 5);
console.log(another);
let worldCities = euroCities.concat(asianCities);
console.log(worldCities);
worldCities.reverse();
console.log(worldCities);
worldCities[2] = "Toronto";
console.log(worldCities);
worldCities.splice(1, 0, "Washington");
console.log(worldCities);
let joinedWolrdCities = worldCities.join("+");
console.log(joinedWolrdCities);
let myString = "Hello World";
let program = myString.split(" ");
program.reverse();
console.log(program);
let sibNames = ["Anji", "Kanna"];
let parentNames = ["Mother", "Father"];
let names = sibNames.concat(parentNames);
console.log(names);
let petNames = ["Heisuke", "Irma"];
petNames.reverse();
console.log(petNames);
parentNames[1] = "Nikolov";
console.log(parentNames);